services:
  - type: web
    name: django-backend
    env: python
    buildCommand: 
      - pip install -r requirements.txt
    startCommand: 
      - "gunicorn ECM2434-v3.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - key: SECRET_KEY
        value: YOUR_SECRET_KEY
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: '0.0.0.0,localhost,127.0.0.1'
        
  - type: web
    name: react-frontend
    env: node
    buildCommand: 
      - npm install
      - npm run build
    startCommand: 
      - serve -s build
